export {default as Home} from './Home.tsx'
export {default as About} from './About.tsx'
export {default as Login} from './Login.tsx'
export {default as Register} from './Register.tsx'
export {default as Product} from './Product.tsx'
export {default as Landing} from './Landing.tsx'
export {default as Error} from './Error.tsx'